### ISSUE TITLE
Brutus needs access to the repo

### ISSUE THREAD

**Issue by rmartin16** [beeware/actions#2]
### Describe the bug

Brutus cannot access the repo:
```
Pushing pull request branch to 'origin/autoupdates/pre-commit/pre-commit-hooks'
  /usr/bin/git push --force-with-lease origin autoupdates/pre-commit/pre-commit-hooks:refs/heads/autoupdates/pre-commit/pre-commit-hooks
  remote: Permission to beeware/actions.git denied to brutusthebee.
  fatal: unable to access 'https://github.com/beeware/actions/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```
source: https://github.com/beeware/actions/actions/runs/9246153096/job/25433383044#step:9:98

### Steps to reproduce

See Actions [failure](https://github.com/beeware/actions/actions/runs/9246153096/job/25433383044#step:9:98).

### Expected behavior

Brutus can checkout and commit to repo.

### Environment

n/a

**Comment by freakboy3742** [comment]
Darn robots, always asking for things... :-)

I've added permissions, and re-run the failed job to confirm, which has passed.
